#击杀时给予经验值
击杀给予经验值:
  #是否启用
  启用: true
  #从掉落经验球中获取经验
  获取掉落经验: false
  #每次击杀给予的经验值(在min-max之间随机)
  经验值:
    min: 1
    max: 3
  #经验等级上限
  等级上限: 500
击杀给予经济:
  启用: true
  经济:
    min: 10.0
    max: 30.0
世界:
  主世界名: world
  #进入游戏时自动回到主世界
  启用: true
  #在这些世界不会自动回到主世界
  排除的世界:
    - world
Player:
  ExamplePlayerName:
    ExpAmount: 0