#击杀时给予经验值
击杀给予经验值:
  #是否启用
  启用: true
  #从掉落经验球中获取经验
  获取掉落经验: false
  #每次击杀给予的经验值(在min-max之间随机)
  经验值:
    min: 1
    max: 3
  #经验等级上限
  等级上限: 500
  主世界: world
Player:
  ExamplePlayerName:
   ChangeExp: false
   ExpAmount: 0